### ISSUE TITLE
problem with run the code

### ISSUE THREAD

**Issue by mbmamin1996** [moberweger/deep-prior#16]
hi when i run the code then 
Traceback (most recent call last):
  File "test_realtimepipeline.py", line 51, in <module>
    Seq2 = di.loadSequence('test_1')
  File "/home/ali/Desktop/deep-prior-master/src/data/importers.py", line 553, in loadSequence
    mat = scipy.io.loadmat(trainlabels)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, 'rb'), True
IOError: [Errno 2] No such file or directory: '../data/NYU//test_1/joint_data.mat'

please help me to solve it

**Comment by moberweger** [comment]
You have to download the nyu dataset and put it to the data directory. The
error states that the file is missing.

aaam <notifications@github.com> schrieb am Sa., 7. Juli 2018 10:10 vorm.:

**Comment by mbmamin1996** [comment]
ok but i cant find joint_data.mat 
i download the data set from this link 
http://horatio.cs.nyu.edu/mit/tompson/nyu_hand_dataset_rdf.zip

**Comment by moberweger** [comment]
I think this is the wrong file. You should download this one:
http://horatio.cs.nyu.edu/mit/tompson/nyu_hand_dataset_v2.zip
